repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        files: ^(apps/api|packages/core)/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        files: ^(apps/api|packages/core)/.*\.py$
      - id: ruff-format
        files: ^(apps/api|packages/core)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        files: ^(apps/api|packages/core)/.*\.py$
        additional_dependencies: [types-all]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.47.0
    hooks:
      - id: eslint
        files: ^apps/web/.*\.(js|jsx|ts|tsx)$
        additional_dependencies:
          - eslint@8.47.0
          - "@typescript-eslint/eslint-plugin@6.4.1"
          - "@typescript-eslint/parser@6.4.1"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
        files: ^apps/web/.*\.(js|jsx|ts|tsx|json|css|md)$