"""Initial migration

Revision ID: d8139676f93e
Revises: 
Create Date: 2025-08-23 12:29:05.938405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8139676f93e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxpayers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxpayers_email'), 'taxpayers', ['email'], unique=True)
    op.create_index(op.f('ix_taxpayers_id'), 'taxpayers', ['id'], unique=False)
    op.create_index(op.f('ix_taxpayers_pan'), 'taxpayers', ['pan'], unique=True)
    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxpayer_id', sa.Integer(), nullable=False),
    sa.Column('assessment_year', sa.String(length=7), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PROCESSED', 'REJECTED', name='taxreturnstatus'), nullable=True),
    sa.Column('return_data', sa.Text(), nullable=True),
    sa.Column('filing_date', sa.DateTime(), nullable=True),
    sa.Column('acknowledgment_number', sa.String(length=50), nullable=True),
    sa.Column('revised_return', sa.Boolean(), nullable=True),
    sa.Column('original_return_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['original_return_id'], ['returns.id'], ),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acknowledgment_number')
    )
    op.create_index(op.f('ix_returns_id'), 'returns', ['id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_return_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tax_return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.create_table('challans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_return_id', sa.Integer(), nullable=False),
    sa.Column('challan_number', sa.String(length=50), nullable=True),
    sa.Column('challan_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('branch_code', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'EXPIRED', name='challanstatus'), nullable=True),
    sa.Column('assessment_year', sa.String(length=7), nullable=False),
    sa.Column('quarter', sa.String(length=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tax_return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challan_number')
    )
    op.create_index(op.f('ix_challans_id'), 'challans', ['id'], unique=False)
    op.create_table('rules_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_return_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=True),
    sa.Column('rule_category', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tax_return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_log_id'), 'rules_log', ['id'], unique=False)
    op.create_table('validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_return_id', sa.Integer(), nullable=False),
    sa.Column('validation_type', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PASSED', 'FAILED', 'WARNING', name='validationstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('field_path', sa.String(length=200), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tax_return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validations_id'), 'validations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validations_id'), table_name='validations')
    op.drop_table('validations')
    op.drop_index(op.f('ix_rules_log_id'), table_name='rules_log')
    op.drop_table('rules_log')
    op.drop_index(op.f('ix_challans_id'), table_name='challans')
    op.drop_table('challans')
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_returns_id'), table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_taxpayers_pan'), table_name='taxpayers')
    op.drop_index(op.f('ix_taxpayers_id'), table_name='taxpayers')
    op.drop_index(op.f('ix_taxpayers_email'), table_name='taxpayers')
    op.drop_table('taxpayers')
    # ### end Alembic commands ###
